SELECT *
FROM geral.CLI_CLIENTES;

SELECT *
FROM geral.PRD_PRODUTOS;

INSERT INTO financeiro.NFE_NOTAS_FISCAIS
(NFE_CHAVE_CONSULTA, CLI_ID)
VALUES
('4PrNUmM45XF31==', 1),
('kmPQrs8A15MOPg1==', 2),
('rsT62Mjuoineg==', 2)
;

SELECT *
FROM financeiro.NFE_NOTAS_FISCAIS;

INSERT INTO financeiro.NIT_ITENS_NOTA_FISCAL
(NIT_QUANTIDADE, NIT_VALOR_UNITARIO, NFE_ID, PRD_ID)
VALUES
(5, 0.50, 4, 9),
(1, 2.79, 5, 3),
(1, 1.19, 6, 8)
;

SELECT 
	cli.CLI_NOME,
	cli.CLI_CPF,
	nfe.NFE_DATA_EMISSAO,
	nit.NIT_QUANTIDADE,
	nit.NIT_VALOR_UNITARIO,
	prd.PRD_NOME,
	prd.PRD_UNIDADE,
	COUNT(nfe.NFE_ID) AS QUANTIDADE_COMPRAS
FROM geral.CLI_CLIENTES cli
JOIN financeiro.NFE_NOTAS_FISCAIS nfe ON cli.CLI_ID = nfe.CLI_ID
JOIN financeiro.NIT_ITENS_NOTA_FISCAL nit ON nfe.NFE_ID = nit.NFE_ID
JOIN geral.PRD_PRODUTOS prd ON nit.PRD_ID = prd.PRD_ID
GROUP BY cli.CLI_NOME,
	cli.CLI_CPF,
	nfe.NFE_DATA_EMISSAO,
	nit.NIT_QUANTIDADE,
	nit.NIT_VALOR_UNITARIO,
	prd.PRD_NOME,
	prd.PRD_UNIDADE
ORDER BY COUNT(nfe.NFE_ID) DESC,
	cli.CLI_NOME
;