CREATE TABLE geral.PRD_PRODUTOS (
	PRD_ID SERIAL PRIMARY KEY,
	PRD_NOME VARCHAR(50) NOT NULL,
	PRD_DESCRICAO TEXT,
	PRD_QUANTIDADE_ESTOQUE DECIMAL(6, 2) NOT NULL,
	PRD_UNIDADE CHAR(2) NOT NULL,
	PRD_ESTA_ATIVO BOOLEAN DEFAULT TRUE
);
