ALTER TABLE CLI_CLIENTES SET SCHEMA geral;

CREATE SCHEMA financeiro;

ALTER TABLE NFE_NOTAS_FISCAIS SET SCHEMA financeiro;

INSERT INTO geral.CLI_CLIENTES
(CLI_NOME, CLI_CPF)
VALUES
('Amábile Nunes', '32259651400'),
('Josias Araújo', '01423698521')
;

SELECT *
FROM geral.CLI_CLIENTES;

INSERT INTO financeiro.NFE_NOTAS_FISCAIS
(NFE_CHAVE_CONSULTA, CLI_ID)
VALUES
('4PrNUmM45XF31==', 1),
('4PrNUmM56PO8x==', 1),
('kmLJCkQUg2MQr4==', 2)
;

SELECT *
FROM financeiro.NFE_NOTAS_FISCAIS;