CREATE SCHEMA autitoria;

ALTER SCHEMA autitoria RENAME TO auditoria;

CREATE TABLE auditoria.log_logs (
	LOG_ID SERIAL PRIMARY KEY,
	LOG_MENSAGEM VARCHAR(600) NOT NULL
);

CREATE OR REPLACE FUNCTION auditoria.FN_TR_INSERCAO_CLIENTE()
RETURNS TRIGGER AS
$$
BEGIN
	INSERT INTO auditoria.log_logs 
	(LOG_MENSAGEM) 
	VALUES
	('O CLIENTE COM ID ' || NEW.CLI_ID::TEXT || ' E NOME ' || NEW.CLI_NOME || ' FOI INSERIDO.');
	RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;

CREATE TRIGGER TR_ANTES_INSERCAO_CLIENTE
BEFORE INSERT ON geral.CLI_CLIENTES
FOR EACH ROW
EXECUTE PROCEDURE auditoria.FN_TR_INSERCAO_CLIENTE();

SELECT *
FROM auditoria.log_logs;

INSERT INTO geral.CLI_CLIENTES
(CLI_NOME, CLI_CPF)
VALUES
('Ana Clara Nogueira Lira', '12345678911')
;

INSERT INTO geral.CLI_CLIENTES
(CLI_NOME, CLI_CPF)
VALUES
('João Pericles Araújo', '02547896321'),
('Mauricio Júnior Ferreira', '04789523221'),
('Josefa Nunes Silva', '37725896545')
;