DROP TRIGGER TR_ANTES_INSERCAO_CLIENTE ON geral.CLI_CLIENTES;

CREATE OR REPLACE FUNCTION auditoria.FN_TR_AUDITORIA_CLIENTES()
RETURNS TRIGGER AS
$$
BEGIN
	IF TG_OP = 'INSERT' THEN
		INSERT INTO auditoria.log_logs 
		(LOG_MENSAGEM) 
		VALUES
		('O CLIENTE COM ID ' || NEW.CLI_ID::TEXT || ' E NOME ' || NEW.CLI_NOME || ' FOI INSERIDO.');
		RETURN NEW;
	ELSIF TG_OP = 'UPDATE' THEN
		INSERT INTO auditoria.log_logs 
		(LOG_MENSAGEM) 
		VALUES
		('O CLIENTE COM ID ' || OLD.CLI_ID::TEXT || ' E NOME ' || OLD.CLI_NOME || ' FOI ATUALIZADO PARA ' || NEW.CLI_NOME);
		RETURN NEW;
	ELSIF TG_OP = 'DELETE' THEN
		INSERT INTO auditoria.log_logs 
		(LOG_MENSAGEM) 
		VALUES
		('O CLIENTE COM ID ' || OLD.CLI_ID::TEXT || ' E NOME ' || OLD.CLI_NOME || ' FOI REMOVIDO.');
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$$
LANGUAGE PLPGSQL;

CREATE TRIGGER TR_AUDITORIA_CLIENTES
BEFORE INSERT OR UPDATE OR DELETE ON geral.CLI_CLIENTES
FOR EACH ROW
EXECUTE PROCEDURE auditoria.FN_TR_AUDITORIA_CLIENTES();

SELECT * 
FROM geral.CLI_CLIENTES;

INSERT INTO geral.CLI_CLIENTES
(CLI_NOME, CLI_CPF)
VALUES
('EDITAR E DELETAR ESTE CLIENTE', '99999999999');

UPDATE geral.CLI_CLIENTES
SET CLI_CPF = '85697412014'
WHERE CLI_CPF = '99999999999';

DELETE FROM geral.CLI_CLIENTES
WHERE CLI_CPF = '85697412014';

SELECT *
FROM auditoria.log_logs;

