-- VIEW

SELECT cli.CLI_NOME,
	COALESCE(SUM(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS VALOR_TOTAL_GASTO,
	COALESCE(MIN(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS MENOR_VALOR_GASTO,
	COALESCE(MAX(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS MAIOR_VALOR_GASTO,
	COALESCE(SUM(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO) / COUNT(nit.NIT_ID), 0::MONEY) AS MEDIA_VALOR_GASTO
FROM geral.CLI_CLIENTES cli
LEFT JOIN financeiro.NFE_NOTAS_FISCAIS nfe ON cli.CLI_ID = nfe.CLI_ID
LEFT JOIN financeiro.NIT_ITENS_NOTA_FISCAL nit ON nfe.NFE_ID = nit.NFE_ID
GROUP BY cli.CLI_NOME
ORDER BY cli.CLI_NOME
;

CREATE VIEW VW_GASTOS_CLIENTE AS
	SELECT cli.CLI_NOME,
		COALESCE(SUM(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS VALOR_TOTAL_GASTO,
		COALESCE(MIN(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS MENOR_VALOR_GASTO,
		COALESCE(MAX(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS MAIOR_VALOR_GASTO,
		COALESCE(SUM(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO) / COUNT(nit.NIT_ID), 0::MONEY) AS MEDIA_VALOR_GASTO
	FROM geral.CLI_CLIENTES cli
	LEFT JOIN financeiro.NFE_NOTAS_FISCAIS nfe ON cli.CLI_ID = nfe.CLI_ID
	LEFT JOIN financeiro.NIT_ITENS_NOTA_FISCAL nit ON nfe.NFE_ID = nit.NFE_ID
	GROUP BY cli.CLI_NOME
	ORDER BY cli.CLI_NOME
;

SELECT *
FROM VW_GASTOS_CLIENTE;

SELECT *
FROM VW_GASTOS_CLIENTE
WHERE CLI_NOME LIKE '%es';

-- MATERIALIZED VIEW

CREATE MATERIALIZED VIEW MVW_GASTOS_CLIENTE AS
	SELECT cli.CLI_NOME,
		COALESCE(SUM(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS VALOR_TOTAL_GASTO,
		COALESCE(MIN(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS MENOR_VALOR_GASTO,
		COALESCE(MAX(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO), 0::MONEY) AS MAIOR_VALOR_GASTO,
		COALESCE(SUM(nit.NIT_QUANTIDADE * nit.NIT_VALOR_UNITARIO) / COUNT(nit.NIT_ID), 0::MONEY) AS MEDIA_VALOR_GASTO
	FROM geral.CLI_CLIENTES cli
	LEFT JOIN financeiro.NFE_NOTAS_FISCAIS nfe ON cli.CLI_ID = nfe.CLI_ID
	LEFT JOIN financeiro.NIT_ITENS_NOTA_FISCAL nit ON nfe.NFE_ID = nit.NFE_ID
	GROUP BY cli.CLI_NOME
	ORDER BY cli.CLI_NOME
;

SELECT *
FROM MVW_GASTOS_CLIENTE;