-- Selecionando campos a serem preenchidos
INSERT INTO GERAL.PRD_PRODUTOS 
(PRD_NOME, PRD_QUANTIDADE_ESTOQUE, PRD_UNIDADE, PRD_ESTA_ATIVO, PRD_CODIGO_BARRAS)
VALUES 
('Cebola', 100.0, 'KG', TRUE, '20304050');

-- Preenchimento default do campo PRD_ESTA_ATIVO
INSERT INTO GERAL.PRD_PRODUTOS 
(PRD_NOME, PRD_QUANTIDADE_ESTOQUE, PRD_UNIDADE, PRD_CODIGO_BARRAS)
VALUES 
('Biscoito', 20, 'UN', '21222324');

-- Violação de constraint not null no campo PRD_UNIDADE
INSERT INTO GERAL.PRD_PRODUTOS 
(PRD_NOME, PRD_QUANTIDADE_ESTOQUE, PRD_CODIGO_BARRAS)
VALUES 
('Biscoito', 20, '21222324');

-- Violação de constraint unique no campo PRD_CODIGO_BARRAS
INSERT INTO GERAL.PRD_PRODUTOS 
(PRD_NOME, PRD_QUANTIDADE_ESTOQUE, PRD_UNIDADE, PRD_CODIGO_BARRAS)
VALUES 
('Batata', 50, 'KG', '21222324');

-- Violação de constraint check no campo PRD_CODIGO_BARRAS
INSERT INTO GERAL.PRD_PRODUTOS 
(PRD_NOME, PRD_QUANTIDADE_ESTOQUE, PRD_UNIDADE, PRD_CODIGO_BARRAS)
VALUES 
('Alho', 8, 'KG', '123');

-- Inserindo várias tuplas ao mesmo tempo
INSERT INTO GERAL.PRD_PRODUTOS 
(PRD_NOME, PRD_QUANTIDADE_ESTOQUE, PRD_UNIDADE, PRD_CODIGO_BARRAS)
VALUES
('Alho', 8, 'KG', '45896315'),
('Pimentão', 16, 'KG', '45896325'),
('Pão', 45, 'KG', '45896345'),
('Balão', 200, 'UN', '45897854'),
('Pneu', 132, 'UN', '20659870')
;

SELECT *
FROM geral.prd_produtos;